# Generated by Django 4.2.28 on 2026-03-30 19:48

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, help_text='Stripe PaymentIntent ID (pi_…)', max_length=255, null=True, unique=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, db_index=True, help_text='Stripe Checkout Session ID (cs_…)', max_length=255, null=True, unique=True)),
                ('order_reference', models.CharField(db_index=True, help_text='Your unique order reference — stored in Stripe metadata.', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('requires_payment_method', 'requires_payment_method'), ('requires_confirmation', 'requires_confirmation'), ('requires_action', 'requires_action'), ('processing', 'processing'), ('requires_capture', 'requires_capture'), ('canceled', 'canceled'), ('succeeded', 'succeeded')], db_index=True, default='requires_payment_method', max_length=50)),
                ('checkout_status', models.CharField(blank=True, choices=[('open', 'open'), ('complete', 'complete'), ('expired', 'expired')], max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in major currency units (e.g. 9.99 for $9.99).', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount actually captured by Stripe.', max_digits=14)),
                ('currency', models.CharField(db_index=True, default='usd', max_length=3)),
                ('payment_method_type', models.CharField(blank=True, help_text='e.g., card, sepa_debit, klarna …', max_length=50, null=True)),
                ('payment_method_id', models.CharField(blank=True, help_text='Stripe PaymentMethod ID (pm_…)', max_length=255, null=True)),
                ('card_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('card_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('card_exp_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('card_exp_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('card_country', models.CharField(blank=True, max_length=2, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, help_text='Stripe Customer ID (cus_…) if payment was made by a customer.', max_length=255, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('checkout_url', models.URLField(blank=True, help_text='Stripe-hosted Checkout URL (for redirect flows).', max_length=2048, null=True)),
                ('receipt_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=100, null=True)),
                ('failure_message', models.TextField(blank=True, null=True)),
                ('client_secret', models.CharField(blank=True, help_text='Stripe client_secret — expose only to the authenticated customer who owns this payment. NEVER log or store permanently in plaintext in a public context.', max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Project-specific metadata attached to the Stripe object.')),
                ('raw_response', models.JSONField(blank=True, help_text='Full raw Stripe API response — for debugging only.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'db_table': 'stripe_payment_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(db_index=True, help_text='Stripe Event ID (evt_…) — used for idempotency.', max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, help_text='e.g., payment_intent.succeeded', max_length=100)),
                ('processing_status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('IGNORED', 'Ignored')], db_index=True, default='RECEIVED', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(help_text='Full Stripe event JSON payload.')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'db_table': 'stripe_webhook_events',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['event_type'], name='stripe_webh_event_t_2d6957_idx'), models.Index(fields=['processing_status'], name='stripe_webh_process_a59367_idx'), models.Index(fields=['-received_at'], name='stripe_webh_receive_d37c92_idx')],
            },
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(db_index=True, help_text='Stripe Customer ID (cus_…)', max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The Django user linked to this Stripe Customer.', on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stripe Customer',
                'verbose_name_plural': 'Stripe Customers',
                'db_table': 'stripe_customers',
            },
        ),
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(db_index=True, help_text='Stripe Subscription ID (sub_…)', max_length=255, unique=True)),
                ('stripe_customer_id', models.CharField(db_index=True, help_text='Stripe Customer ID (cus_…)', max_length=255)),
                ('stripe_price_id', models.CharField(help_text='Stripe Price ID (price_…) for the subscribed plan.', max_length=255)),
                ('stripe_product_id', models.CharField(blank=True, help_text='Stripe Product ID (prod_…)', max_length=255, null=True)),
                ('status', models.CharField(choices=[('incomplete', 'incomplete'), ('incomplete_expired', 'incomplete_expired'), ('trialing', 'trialing'), ('active', 'active'), ('past_due', 'past_due'), ('canceled', 'canceled'), ('unpaid', 'unpaid'), ('paused', 'paused')], db_index=True, default='incomplete', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Recurring billing amount in major currency units.', max_digits=14)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('interval', models.CharField(blank=True, help_text='Billing interval: day, week, month, year.', max_length=10, null=True)),
                ('interval_count', models.PositiveIntegerField(default=1, help_text='Number of intervals between billings.')),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'stripe_subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stripe_customer_id'], name='stripe_subs_stripe__627faf_idx'), models.Index(fields=['status'], name='stripe_subs_status_8578d7_idx'), models.Index(fields=['current_period_end'], name='stripe_subs_current_a134e2_idx'), models.Index(fields=['-created_at'], name='stripe_subs_created_373daa_idx')],
            },
        ),
        migrations.CreateModel(
            name='StripeRefundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_refund_id', models.CharField(db_index=True, help_text='Stripe Refund ID (re_…)', max_length=255, unique=True)),
                ('order_reference', models.CharField(db_index=True, help_text='Copied from the original payment for easy lookup.', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('requires_action', 'requires_action'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('canceled', 'canceled')], db_index=True, default='pending', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Refund amount in major currency units.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('reason', models.CharField(blank=True, help_text='duplicate | fraudulent | requested_by_customer | other', max_length=100, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_refunds_initiated', to=settings.AUTH_USER_MODEL)),
                ('payment_transaction', models.ForeignKey(help_text='The original payment this refund belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='stripe_payments.stripepaymenttransaction')),
            ],
            options={
                'verbose_name': 'Refund Transaction',
                'verbose_name_plural': 'Refund Transactions',
                'db_table': 'stripe_refund_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_reference'], name='stripe_refu_order_r_996225_idx'), models.Index(fields=['status'], name='stripe_refu_status_4ebcb0_idx'), models.Index(fields=['-created_at'], name='stripe_refu_created_d188ce_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stripepaymenttransaction',
            index=models.Index(fields=['order_reference'], name='stripe_paym_order_r_71829d_idx'),
        ),
        migrations.AddIndex(
            model_name='stripepaymenttransaction',
            index=models.Index(fields=['status'], name='stripe_paym_status_17a6ae_idx'),
        ),
        migrations.AddIndex(
            model_name='stripepaymenttransaction',
            index=models.Index(fields=['currency'], name='stripe_paym_currenc_d65214_idx'),
        ),
        migrations.AddIndex(
            model_name='stripepaymenttransaction',
            index=models.Index(fields=['stripe_customer_id'], name='stripe_paym_stripe__e297ef_idx'),
        ),
        migrations.AddIndex(
            model_name='stripepaymenttransaction',
            index=models.Index(fields=['-created_at'], name='stripe_paym_created_de8553_idx'),
        ),
        migrations.AddIndex(
            model_name='stripecustomer',
            index=models.Index(fields=['stripe_customer_id'], name='stripe_cust_stripe__2ea2de_idx'),
        ),
    ]
